//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyAdmin.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TemplateAFIS12 {
            get {
                return ((string)(this["TemplateAFIS12"]));
            }
            set {
                this["TemplateAFIS12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TemplateInvoiceWord {
            get {
                return ((string)(this["TemplateInvoiceWord"]));
            }
            set {
                this["TemplateInvoiceWord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TemplateInvoiceWordReseller {
            get {
                return ((string)(this["TemplateInvoiceWordReseller"]));
            }
            set {
                this["TemplateInvoiceWordReseller"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TemplateInvoiceWordDiscount {
            get {
                return ((string)(this["TemplateInvoiceWordDiscount"]));
            }
            set {
                this["TemplateInvoiceWordDiscount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SaveDirAFIS12 {
            get {
                return ((string)(this["SaveDirAFIS12"]));
            }
            set {
                this["SaveDirAFIS12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SaveDirInvoice {
            get {
                return ((string)(this["SaveDirInvoice"]));
            }
            set {
                this["SaveDirInvoice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SaveDirInvoiceReseller {
            get {
                return ((string)(this["SaveDirInvoiceReseller"]));
            }
            set {
                this["SaveDirInvoiceReseller"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TemplateHeader {
            get {
                return ((string)(this["TemplateHeader"]));
            }
            set {
                this["TemplateHeader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("21.0")]
        public decimal FATHigh {
            get {
                return ((decimal)(this["FATHigh"]));
            }
            set {
                this["FATHigh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6.0")]
        public decimal FATLow {
            get {
                return ((decimal)(this["FATLow"]));
            }
            set {
                this["FATLow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000, 1000")]
        public global::System.Drawing.Size MainFormWindowSize {
            get {
                return ((global::System.Drawing.Size)(this["MainFormWindowSize"]));
            }
            set {
                this["MainFormWindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState MainFormWindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["MainFormWindowState"]));
            }
            set {
                this["MainFormWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30, 10")]
        public global::System.Drawing.Point MainFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["MainFormLocation"]));
            }
            set {
                this["MainFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PDFOutputInvoice {
            get {
                return ((string)(this["PDFOutputInvoice"]));
            }
            set {
                this["PDFOutputInvoice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal DecimalsInvoiceAmount {
            get {
                return ((decimal)(this["DecimalsInvoiceAmount"]));
            }
            set {
                this["DecimalsInvoiceAmount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PDFOutputAFIS {
            get {
                return ((string)(this["PDFOutputAFIS"]));
            }
            set {
                this["PDFOutputAFIS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal InvoiceNoOffset {
            get {
                return ((decimal)(this["InvoiceNoOffset"]));
            }
            set {
                this["InvoiceNoOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool InvoiceAmountRemove0s {
            get {
                return ((bool)(this["InvoiceAmountRemove0s"]));
            }
            set {
                this["InvoiceAmountRemove0s"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30000")]
        public decimal EmailTimeout {
            get {
                return ((decimal)(this["EmailTimeout"]));
            }
            set {
                this["EmailTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("vandeputbv@online.nl")]
        public string EmailFrom {
            get {
                return ((string)(this["EmailFrom"]));
            }
            set {
                this["EmailFrom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("smtp.online.nl")]
        public string EmailSMTPServer {
            get {
                return ((string)(this["EmailSMTPServer"]));
            }
            set {
                this["EmailSMTPServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public decimal EmailSMTPPort {
            get {
                return ((decimal)(this["EmailSMTPPort"]));
            }
            set {
                this["EmailSMTPPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EmailSMTPSSL {
            get {
                return ((bool)(this["EmailSMTPSSL"]));
            }
            set {
                this["EmailSMTPSSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bitankbv@gmail.com")]
        public string EmailSMTPUser {
            get {
                return ((string)(this["EmailSMTPUser"]));
            }
            set {
                this["EmailSMTPUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EmailSMTPPassw {
            get {
                return ((string)(this["EmailSMTPPassw"]));
            }
            set {
                this["EmailSMTPPassw"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ccvkb@nl.ccv.eu")]
        public string EmailCCV {
            get {
                return ((string)(this["EmailCCV"]));
            }
            set {
                this["EmailCCV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SaveDirYearSubFolder {
            get {
                return ((bool)(this["SaveDirYearSubFolder"]));
            }
            set {
                this["SaveDirYearSubFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DB_UseWinAuth {
            get {
                return ((bool)(this["DB_UseWinAuth"]));
            }
            set {
                this["DB_UseWinAuth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3306")]
        public decimal DB_Port {
            get {
                return ((decimal)(this["DB_Port"]));
            }
            set {
                this["DB_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost")]
        public string DB_Server {
            get {
                return ((string)(this["DB_Server"]));
            }
            set {
                this["DB_Server"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("root")]
        public string DB_Username {
            get {
                return ((string)(this["DB_Username"]));
            }
            set {
                this["DB_Username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DB_Psw {
            get {
                return ((string)(this["DB_Psw"]));
            }
            set {
                this["DB_Psw"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("vdput")]
        public string DB_Database {
            get {
                return ((string)(this["DB_Database"]));
            }
            set {
                this["DB_Database"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("customers")]
        public string DBTbl_customers {
            get {
                return ((string)(this["DBTbl_customers"]));
            }
            set {
                this["DBTbl_customers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ccvcards")]
        public string DBTbl_ccvcards {
            get {
                return ((string)(this["DBTbl_ccvcards"]));
            }
            set {
                this["DBTbl_ccvcards"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("invoices")]
        public string DBTbl_invoices {
            get {
                return ((string)(this["DBTbl_invoices"]));
            }
            set {
                this["DBTbl_invoices"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("products")]
        public string DBTbl_products {
            get {
                return ((string)(this["DBTbl_products"]));
            }
            set {
                this["DBTbl_products"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("afis12")]
        public string DBTbl_afis12 {
            get {
                return ((string)(this["DBTbl_afis12"]));
            }
            set {
                this["DBTbl_afis12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("emailsend")]
        public string DBTbl_emailsend {
            get {
                return ((string)(this["DBTbl_emailsend"]));
            }
            set {
                this["DBTbl_emailsend"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("emailattachm")]
        public string DBTbl_emailattch {
            get {
                return ((string)(this["DBTbl_emailattch"]));
            }
            set {
                this["DBTbl_emailattch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MySql")]
        public string DB_dbtype {
            get {
                return ((string)(this["DB_dbtype"]));
            }
            set {
                this["DB_dbtype"] = value;
            }
        }
    }
}
